P8105_hw1_mcm2335
================
Madeleine McGuinness
09/23/2023

# Problem 1

## This problem focuses on the use of inline R code, plotting, and the behavior of ggplot for variables of different types.

``` r
#step 1: load packages

library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(moderndive)
library(dplyr)

#step 2: load "early_janurary_weather" dataset

data("early_january_weather") # load the data

#step 3: describe the data and get mean temp

names(early_january_weather) # this function gathers the names of all variables in the dataframe
```

    ##  [1] "origin"     "year"       "month"      "day"        "hour"      
    ##  [6] "temp"       "dewp"       "humid"      "wind_dir"   "wind_speed"
    ## [11] "wind_gust"  "precip"     "pressure"   "visib"      "time_hour"

``` r
view(early_january_weather) # this functions pulls up the entire table in another tab

nrow(early_january_weather) # this functions pulls up the number of rows in the dataframe
```

    ## [1] 358

``` r
ncol(early_january_weather) # this functions pulls up the number of columns in the dataframe
```

    ## [1] 15

``` r
head(early_january_weather) # this function pulls up the first 6 rows in the table
```

    ## # A tibble: 6 × 15
    ##   origin  year month   day  hour  temp  dewp humid wind_dir wind_speed wind_gust
    ##   <chr>  <int> <int> <int> <int> <dbl> <dbl> <dbl>    <dbl>      <dbl>     <dbl>
    ## 1 EWR     2013     1     1     1  39.0  26.1  59.4      270      10.4         NA
    ## 2 EWR     2013     1     1     2  39.0  27.0  61.6      250       8.06        NA
    ## 3 EWR     2013     1     1     3  39.0  28.0  64.4      240      11.5         NA
    ## 4 EWR     2013     1     1     4  39.9  28.0  62.2      250      12.7         NA
    ## 5 EWR     2013     1     1     5  39.0  28.0  64.4      260      12.7         NA
    ## 6 EWR     2013     1     1     6  37.9  28.0  67.2      240      11.5         NA
    ## # ℹ 4 more variables: precip <dbl>, pressure <dbl>, visib <dbl>,
    ## #   time_hour <dttm>

``` r
tail(early_january_weather) # this function fulls up the last 6 rows in the table
```

    ## # A tibble: 6 × 15
    ##   origin  year month   day  hour  temp  dewp humid wind_dir wind_speed wind_gust
    ##   <chr>  <int> <int> <int> <int> <dbl> <dbl> <dbl>    <dbl>      <dbl>     <dbl>
    ## 1 EWR     2013     1    15    18  39.0  26.1  59.4      360       5.75        NA
    ## 2 EWR     2013     1    15    19  37.9  26.1  61.9       10       4.60        NA
    ## 3 EWR     2013     1    15    20  37.9  25.0  59.2       20       6.90        NA
    ## 4 EWR     2013     1    15    21  37.9  27.0  64.3       30       5.75        NA
    ## 5 EWR     2013     1    15    22  37.0  28.9  72.2       20       8.06        NA
    ## 6 EWR     2013     1    15    23  36.0  30.0  78.8       20       9.21        NA
    ## # ℹ 4 more variables: precip <dbl>, pressure <dbl>, visib <dbl>,
    ## #   time_hour <dttm>

``` r
skimr::skim(early_january_weather)
```

|                                                  |                       |
|:-------------------------------------------------|:----------------------|
| Name                                             | early_january_weather |
| Number of rows                                   | 358                   |
| Number of columns                                | 15                    |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |                       |
| Column type frequency:                           |                       |
| character                                        | 1                     |
| numeric                                          | 13                    |
| POSIXct                                          | 1                     |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |                       |
| Group variables                                  | None                  |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| origin        |         0 |             1 |   3 |   3 |     0 |        1 |          0 |

**Variable type: numeric**

| skim_variable | n_missing | complete_rate |    mean |     sd |      p0 |     p25 |     p50 |     p75 |    p100 | hist  |
|:--------------|----------:|--------------:|--------:|-------:|--------:|--------:|--------:|--------:|--------:|:------|
| year          |         0 |          1.00 | 2013.00 |   0.00 | 2013.00 | 2013.00 | 2013.00 | 2013.00 | 2013.00 | ▁▁▇▁▁ |
| month         |         0 |          1.00 |    1.00 |   0.00 |    1.00 |    1.00 |    1.00 |    1.00 |    1.00 | ▁▁▇▁▁ |
| day           |         0 |          1.00 |    8.04 |   4.31 |    1.00 |    4.00 |    8.00 |   12.00 |   15.00 | ▇▇▇▇▇ |
| hour          |         0 |          1.00 |   11.53 |   6.92 |    0.00 |    6.00 |   11.50 |   17.75 |   23.00 | ▇▇▆▇▇ |
| temp          |         0 |          1.00 |   39.58 |   7.06 |   24.08 |   33.98 |   39.02 |   44.96 |   57.92 | ▃▇▇▇▁ |
| dewp          |         0 |          1.00 |   28.06 |  10.73 |    8.96 |   19.94 |   26.06 |   35.06 |   53.06 | ▃▇▆▂▃ |
| humid         |         0 |          1.00 |   65.48 |  18.95 |   32.86 |   51.34 |   61.67 |   78.68 |  100.00 | ▃▇▆▂▅ |
| wind_dir      |         5 |          0.99 |  208.19 | 115.58 |    0.00 |  140.00 |  240.00 |  290.00 |  360.00 | ▅▁▂▇▆ |
| wind_speed    |         0 |          1.00 |    8.23 |   4.61 |    0.00 |    5.75 |    8.06 |   11.51 |   24.17 | ▅▇▆▂▁ |
| wind_gust     |       308 |          0.14 |   22.53 |   3.63 |   16.11 |   19.56 |   21.86 |   25.32 |   31.07 | ▅▇▃▇▁ |
| precip        |         0 |          1.00 |    0.00 |   0.01 |    0.00 |    0.00 |    0.00 |    0.00 |    0.19 | ▇▁▁▁▁ |
| pressure      |        38 |          0.89 | 1022.52 |   5.57 | 1010.80 | 1018.30 | 1022.05 | 1027.23 | 1034.40 | ▃▇▇▇▃ |
| visib         |         0 |          1.00 |    8.52 |   3.00 |    0.12 |    9.00 |   10.00 |   10.00 |   10.00 | ▁▁▁▁▇ |

**Variable type: POSIXct**

| skim_variable | n_missing | complete_rate | min                 | max                 | median              | n_unique |
|:--------------|----------:|--------------:|:--------------------|:--------------------|:--------------------|---------:|
| time_hour     |         0 |             1 | 2013-01-01 01:00:00 | 2013-01-15 23:00:00 | 2013-01-08 12:30:00 |      358 |

``` r
mean(early_january_weather$temp) # this functions takes the mean of the temperature variable
```

    ## [1] 39.58212

``` r
#step 4: create scatterplot of temp(y) vs time_hour(x) and save

early_january_temperature_by_time <- early_january_weather %>% 
  ggplot(aes(x = time_hour, y = temp, color = humid)) + 
  geom_point(alpha = .5)

ggsave("early_january_temperature_by_time.pdf")
```

    ## Saving 7 x 5 in image

## Problem 1 Answers

Looking at the environment panel, the dataset “early_janurary_weather”
has 15 variables (origin, year, month, day, hour, temp, dewp, humid,
wind_dir, windspeed, precip, pressure, visib, and time_hour) with 358
observations each. Using the ‘nrow’ and ‘ncol’ functions, it is
confirmed that there are 15 columns and 358 rows in the dataframe.

By viewing the data with the view(), head(), and tail() functions, it
appears that this data includes climate measure readings taken every
hour at one particular weather station (EWR) from January 1st through
January 15th of 2013. The skimr::skim function tells us that there is
one character variable (origin), 13 integer or numeric variables (year,
month, day, hour, temp, dewp, humid, wind_dir, wind_speed, wind_gust,
precip, pressure, and visib) and one POSIXct variable (time_hour) that
includes the date and time of each climate/weather reading. There are no
group variables. There is missingness in the wind_gust (308 NAs) and
pressure (38 NAs) columns, and it appears that every row with an NA
value for pressure also has an NA value for wind_gust.

The mean function ‘mean(early_january_weather\$temp)’ tells us that the
mean temperature using hourly readings from January 1st through 15th of
2013 at the EWR station was 39.58 degrees.

In the scatterplot created of temp(y) vs time_hour(x), we can see that
the daily temperature as a trend increased gradually from January 1st
through 15th, although there is hourly variation as the temperature
fluctuates from highs to lows each day. By setting the color of the
points in the scatterplot to the ‘humid’ variable, we can also see that
there is an overall upward trend in humidity as the average temperature
in January increases from January 1st to January 15th.

# Problem 2

## This problem is intended to emphasize variable types and introduce coercion; some awareness of how R treats numeric, character, and factor variables is necessary for working with these data types in practice.

``` r
# Instructions: Create a data frame comprised of:
#a random sample of size 10 from a standard Normal distribution
#a logical vector indicating whether elements of the sample are greater than 0
#a character vector of length 10
#a factor vector of length 10, with 3 different factor “levels”

# step 1: set seed to make sure sampling is consistent when run multiple times
set.seed(123)

#step 2: create dataframe
numeric_values <- rnorm(10)

#step 3: create logical vector
logical_vector <- numeric_values > 0

#step 4: character vector
character_vector <- vector("character", length = 10)

#step 5: factor vector
factor_vector <- factor(c("a", "b", "c", "a", "b", "c", "a", "b", "c", "a"))

#step 6: create the dataframe
df <- tibble(numeric_values, logical_vector, character_vector, factor_vector)

#step 7: take the means of each variable
mean_numeric <- mean(df$numeric_values) #0.0746
mean_logical <- mean(df$logical_vector) #0.5 (proportion of True to False)
mean_character <- mean(df$character_vector) # returns NA because not numeric or logical
```

    ## Warning in mean.default(df$character_vector): argument is not numeric or
    ## logical: returning NA

``` r
mean_factor <- mean(df$factor_vector) # returns NA because not numeric or logical
```

    ## Warning in mean.default(df$factor_vector): argument is not numeric or logical:
    ## returning NA

``` r
#step 8: take the means of each non-numeric variable as numeric
logical_as_numeric <- as.numeric(logical_vector)
mean(logical_as_numeric) # returns 0.5, same as before

character_as_numeric <- as.numeric(character_vector) # returns all NAs
mean(character_as_numeric) # mean is NA

factor_as_numeric <- as.numeric(factor_vector) # converts factors into their levels
mean(factor_as_numeric) # returns numeric mean of factors as their levels, 1.9
```

## Problem 2 Answers

I was able to take the mean of both the numeric and logical vectors. The
mean of my numeric vector was the average of each numeric value in the
vector. The mean of the logical vector treated each ‘False’ value as ‘0’
and each ‘True’ value as ‘1’ and because there was an equal distribution
of 0s and 1s in the vector, returned a mean of 0.5. I was not able to
take the mean of the charactor vector and the factor vectors and both
returned ‘NA’ as the result. However, when I converted the factor vector
to numeric, each factor was assigned an integer that corresponded to its
factor level, and I was able to get a numeric mean. Treating my
character vector as numeric still resulted in a mean of ‘NA’.
